### ISSUE TITLE
Re-add icon toolchain

### ISSUE THREAD

**Issue by mvsde** [pangolinjs/core#16]
Re-integrate icon toolchain from styleguide v3 but with more options:
* ~Copy loose files~ (Already handled by copy plugin)
* Create SVG sprite
* ~Create icon font~ (Icon fonts are considered bad practice and shouldn't be used anymore)

**Comment by mvsde** [comment]
Might be worth looking into:
https://github.com/kisenka/svg-sprite-loader

**Comment by thommyhh** [comment]
@mvsde How's your progress on this one? I'd really like to have this. I tried myself, but had no idea where to start....

**Comment by mvsde** [comment]
@thommyhh I've finally found some time to continue the general development. But I still have to look into the webpack integration for this specific issue. I may have to write a custom loader/plugin to implement the behavior of prior styleguide versions.

**Comment by mvsde** [comment]
The current best practice for icons:
* SVG sprite
* SVG inlining

Both should be done by hand for best SVG optimization.
