### ISSUE TITLE
Use webpack-chain to allow more advanced project level config overrides

### ISSUE THREAD

**Issue by mvsde** [pangolinjs/core#23]
[webpack-chain](https://github.com/mozilla-neutrino/webpack-chain) is a great project by Mozilla which allows modification of the webpack config. It's a lot more advanced than a simple merging of two configs.

This allows direct modification of loader and plugin configuration on a project level.

**Comment by thommyhh** [comment]
Will this also allow changing Imagemin plugin configuration?

I've the problem, the my SVG sprite get's cleared out (all symbols removed). Any way to avoid this, right now with 4.x?

**Comment by mvsde** [comment]
The latest release v4.8.0 keeps unused symbols in SVG files.

**Comment by thommyhh** [comment]
@mvsde That's nice, but it has one bug. The symbols' id is removed, so i still can't reference them in the <use> tag.

**Comment by mvsde** [comment]
@thommyhh The imagemin configuration is now fully customizable in the latest release v4.9.0: https://pangolinjs.org/v4/configuration.html#imagemin-config

**Comment by thommyhh** [comment]
@mvsde Works as expected, thank you for your help. :-)
