### ISSUE TITLE
Cannot install @pangolin/cli

### ISSUE THREAD

**Issue by akmur** [pangolinjs/core#31]
Hi, I opened a similar ticket an hour ago, but now the issue I get is similar but different

Now the installation runs until the end, however when I try to create a project in the end I still get:

```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Cannot read property 'match' of undefined
```

**Comment by mvsde** [comment]
I have to go trough all of the packages and fix this issue. Thanks again for bringing this up 🙂

**Comment by mvsde** [comment]
The installation with npm should work now. I still have no idea why npm suddenly doesn't like the `npm-shrinkwrap.json` anymore.
