### ISSUE TITLE
Not possible to run dev server inside docker

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#36]
Due to a hardcoded `localhost` value for the listening interface of the webpack dev server, it is not possible to run the dev server inside a docker container and expose the port to the host.

The problem could be easily fixed by changing `dev.js` line 55 to `server.listen(serverPort, '0.0.0.0', () => {` to make the dev server listen on all interfaces. The websocket server is already listening on all interfaces.

**Comment by mvsde** [comment]
The [beta 13 release](/pangolinjs/core/releases/v5.0.0-beta.13) has three new ways to set a different hostname:

**[pangolin.config.js](https://pangolinjs.org/guide/configuration.html#dev-server)**
```js
module.exports = {
  devServer: {
    host: 'hostname'
  }
}
```

**[Environment variable](https://pangolinjs.org/guide/configuration.html#environment-variables)**
```bash
export PANGOLIN_ENV=hostname
```

**[CLI argument](https://pangolinjs.org/guide/pangolin-core.html#dev)**
```bash
pangolin-core dev --host hostname
```

**Comment by thommyhh** [comment]
Thanks for the quick response. I just looked at the code. It looks to me, that if I now use `0.0.0.0` as hostname, it would e.g. display `http://0.0.0.0:3000` as the url to the dev server. I will give it a try anyway.

**Comment by thommyhh** [comment]
@mvsde It tried beta13 and it works great. I can set the host now.

But as I expected `http://0.0.0.0:3000` is displayed as where to find the dev server. This is more a cosmetic change, but it would be nice, if the options would be `listenHost` (which I would set to `0.0.0.0` in my case) and `webHost` which still could be set to `localhost`.

**Comment by mvsde** [comment]
Since 5.0.0-beta.14 the new default hostname is `0.0.0.0`. If Node runs in a container, the logged host will be "prettified".

So explicitly setting the host to `0.0.0.0` is no longer necessary.

**Comment by thommyhh** [comment]
@mvsde Awesome, thank you. :-)
