### ISSUE TITLE
Allow changing all aspects of webpacks dev server

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#37]
The configuration directive `devServer` in `pangolin.config.js` suggest, that this would be used by the webpack dev server, but it obviously is not.

Please allow this by e.g. using all settings from `store.state.config.devServer` as default and override the necessary settings like in `dev.js` ll. 60 - 71. This way it would be possible to set something like `disableHostCheck` or `allowedHosts' in the project settings, which I need, because the dev server is accessible through a local development proxy.

**Comment by mvsde** [comment]
The dev server now consumes the already available configuration options from the webpack config: https://pangolinjs.org/guide/configuration.html#dev-server

**Comment by thommyhh** [comment]
@mvsde I think this is still not complete. The first configuration example
```
module.exports = {
  devServer: {
    // Set the desired UI host
    // Default: '0.0.0.0'
    host: '127.0.0.1',
    // Set the desired UI port
    // Default: 8080
    port: 1337
  }
}
```
does not work. As far as I can see in the process of config generation, the `devServer` directive at config root level is never used. It does work though, when setting the settings in the `configure` function.

**Comment by mvsde** [comment]
Hm… I don’t fully understand the problem.

The `devServer` key in the optional `pangolin.config.js` file is the first source that is used for the dev server. The environment variables `PANGOLIN_HOST` and `PANGOLIN_PORT` overwrite these. And last come the flags `--host <some host>` and `--port <some port>` for the `pangolin-core dev` command (`npm run dev` in `package.json`).
