### ISSUE TITLE
Warning: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#39]
Due to some changes in webpack the warning is shown. It goes away, when I uncomment the line `config = require(path.join(context, 'pangolin.config.js'))` in `get-config.js`.

**Comment by mvsde** [comment]
Can you provide your `pangolin.config.js` settings and a full stack trace for this error?

**Comment by mvsde** [comment]
The beta release [v5.0.0-beta.16](/pangolinjs/core/releases/tag/v5.0.0-beta.16) contains a refactored user config loading mechanism. Does this issue still exist?

**Comment by thommyhh** [comment]
@mvsde This does unfortunately not fix the issues.

**Comment by mvsde** [comment]
Can you provide the full stack trace for the error? Currently I can't reproduce the error.

**Comment by thommyhh** [comment]
@mvsde The error seems to be not related with your code, but with mine. I tried to use the nunjucks `static` extension in the browser, which caused really strange errors. After I replaced that with my own implementation all errors are gone.

Thanks for feedback and support. I close this issue.
