### ISSUE TITLE
Pangolin not working with IE 11

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#83]
I just ran into an issue, where the generated code did not work in IE 11 even though I used babel with `preset-env` and a `.browserlistrc` that included IE 11. After some research I found out, that the webpack bundliing produces ES6 code containing arrow functions.

I added the following to my `pangolin.config.js`:
```
module.exports = {
    ...
    configure(config) {
        config.output.ecmaVersion = 5
    },
    ...
}
```
to solve this. => https://webpack.js.org/configuration/output/#outputecmaversion

Could you include this or either add a note to the documentation.

Furthermore the dev server with pangolin does not work in IE 11 either because of some arrow functions in the pangolin code. This means testing in IE 11 requires a production or at least a dev build, which is quite annoying. It would also be nice, if used dependencies from `node_modules` would be transformed with babel.

I know, IE 11 is old, but still needs to be supported in the most projects.

**Comment by mvsde** [comment]
That's an interesting one. I thought the `@babel/preset-env` would take care of everything (including arrow functions). I'll investigate over the weekend.

**Comment by thommyhh** [comment]
Well it does handle arrow functions, but it does handle only the code I've written in the project, not including dependencies in `node_modules` folder or the pangolin code.

**Comment by mvsde** [comment]
* The Pangolin.js UI is now transpiled for older browsers.
* Dependencies can be explicitly transpiled: https://pangolinjs.org/guide/configuration.html#transpile-dependencies
