### ISSUE TITLE
File hashing for main JS and CSS files

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#88]
It would be nice, if the option `fileNameHash` would be used when emitting the main JS & CSS (including vendor) files. Additionally the `webpack-manifest-plugin` should be used to generate a manifest file.

This is e.g. supported by the Symfony framework to automatically include the correct files, when using hashes as cache busting mechanism.

Any chance, that you could include this?

**Comment by mvsde** [comment]
I will look into this.

For reference: https://github.com/danethurber/webpack-manifest-plugin

**Comment by mvsde** [comment]
This has been implemented in release: [v5.7.0](https://github.com/pangolinjs/core/releases/tag/v5.7.0)

Documentation: https://pangolinjs.org/guide/configuration.html#filename-hashing-and-manifest
